name: Auto-Approve for @edarruiz
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'edarruiz'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto-approved by automated PR."
